# Generated by Django 4.1.5 on 2023-01-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('data', models.CharField(max_length=10)),
                ('valor', models.IntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('cartao', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=10)),
                ('dono_da_loja', models.CharField(max_length=50)),
                ('nome_da_loja', models.CharField(max_length=50)),
            ],
        ),
    ]
